### ISSUE TITLE
Full docker-compose example

### ISSUE THREAD

**Issue by vergissberlin** [panubo/docker-s3-backup#1]
*Hi!*

That you for developing this! A _docker-compose_ file should look like this or?

```
version: '2'
services:
  backup-data:
    image: panubo/s3-backup
    environment:
      - BACKUP_KEEP=30
      - BACKUP_DST=example/path
      - BACKUP_SRC=/var/example/path
      - AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXX
      - AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - AWS_STORAGE_BUCKET_NAME=example-bucket
```

Did I miss something? I got the message "fuse: device not found, try 'modprobe fuse' first"

Thank you!
André
